Add entities, interface IRepository, repositories for entities
Dev-incubator/WebAutoparkDenis pull request #1
Opened 2021-12-07 11:46 UTC by DenisCo1100100

2021-12-08 17:50 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/Base/BaseRepository.cs
> +    public abstract class BaseRepository
Why BaseRepository?
This class provide connection initialization

2021-12-08 17:50 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/Base/BaseRepository.cs
> +        protected readonly DbConnection DataBase;
Data`b`ase or DbConnection

2021-12-08 17:50 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/Base/IRepository.cs
> +        public IEnumerable<T> GetAllItems();
```suggestion
        IEnumerable<T> GetAllItems();
```
It`s redundant at IRepository, because all interface methods public by default

2021-12-08 17:50 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/Base/IRepository.cs
> +    interface IRepository<T>
```suggestion
    public interface IRepository<T> 
```

2021-12-08 17:50 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/Base/BaseRepository.cs
> +    public abstract class BaseRepository
Why u don`t dispose this connection?

2021-12-08 17:50 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/ComponentRepository.cs
> +    class ComponentRepository : BaseRepository, IRepository<Component>
All repositories should be public

2021-12-08 18:34 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/BaseRepository.cs
> +    public abstract class BaseRepository
Fixed

2021-12-08 18:34 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/BaseRepository.cs
> +        protected readonly DbConnection DataBase;
Fixed

2021-12-08 18:34 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/IRepository.cs
> +        public IEnumerable<T> GetAllItems();
Fixed

2021-12-08 18:35 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/IRepository.cs
> +    interface IRepository<T>
Fixed

2021-12-08 18:35 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/ComponentRepository.cs
> +    class ComponentRepository : BaseRepository, IRepository<Component>
Fixed

2021-12-09 22:07 UTC, PushMeNow commented on WebAutopark.DataBaseAccess/Repository/Base/ConnectionRepository.cs
> +        protected readonly DbConnection DataBaseConnection;
Just Connection

2021-12-09 22:09 UTC, PushMeNow commented on WebAutopark.DataBaseAccess/Repository/Base/ConnectionRepository.cs
> +        protected ConnectionRepository(string connectionString)
Create ConnectionStringProvider to provide connection string.

2021-12-13 13:09 UTC, DenisCo1100100 commented on WebAutopark.Core/Enums/ColorType.cs
> +        Grean,
Fixed

2021-12-13 13:09 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/ConnectionRepository.cs
> +    public abstract class ConnectionRepository : IDisposable
Fixed

2021-12-13 13:09 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/ConnectionRepository.cs
> +        protected readonly DbConnection DataBaseConnection;
Fixed

2021-12-13 13:09 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/Base/ConnectionRepository.cs
> +        protected ConnectionRepository(string connectionString)
Fixed

2021-12-14 20:02 UTC, PushMeNow requested changes

2021-12-14 20:56 UTC, DenisCo1100100 commented on SQLScripts/dbo.Components.Table.sql
> +	[Name] [nchar](50) NULL,
fixed

2021-12-14 20:57 UTC, DenisCo1100100 commented on SQLScripts/dbo.VehicleTypes.Table.sql
> +	[Name] [nchar](50) NULL,
fixed, ok

2021-12-14 22:34 UTC, DenisCo1100100 commented on SQLScripts/dbo.Orders.Table.sql
> +	[VehicleId] [int] NULL,
fixed

2021-12-14 22:34 UTC, DenisCo1100100 commented on SQLScripts/dbo.Vehicles.Table.sql
> +	[Color] [int] NULL,
fixed

2021-12-17 16:38 UTC, PushMeNow requested changes

2021-12-17 16:38 UTC, PushMeNow commented on SQLScripts/dbo.OrderItems.Table.sql
> +ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Orders] FOREIGN KEY([OrderItemId])
OrderItemId could not reffer to OrderId

2021-12-17 16:38 UTC, PushMeNow commented on SQLScripts/dbo.Orders.Table.sql
> +ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Vehicles] FOREIGN KEY([OrdersId])
OrdersId could not reffer to VehicleId

2021-12-17 16:38 UTC, PushMeNow commented on SQLScripts/dbo.Vehicles.Table.sql
> +ALTER TABLE [dbo].[Vehicles]  WITH CHECK ADD  CONSTRAINT [FK_Vehicles_VehicleTypes] FOREIGN KEY([VehicleId])
VehicleId cannot reffer to VehicleTypeId

2021-12-18 12:30 UTC, DenisCo1100100 commented on SQLScripts/dbo.OrderItems.Table.sql
> +ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Orders] FOREIGN KEY([OrderItemId])
Fixed

2021-12-18 12:30 UTC, DenisCo1100100 commented on SQLScripts/dbo.Orders.Table.sql
> +ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Vehicles] FOREIGN KEY([OrdersId])
Fixed

2021-12-18 12:30 UTC, DenisCo1100100 commented on SQLScripts/dbo.Vehicles.Table.sql
> +ALTER TABLE [dbo].[Vehicles]  WITH CHECK ADD  CONSTRAINT [FK_Vehicles_VehicleTypes] FOREIGN KEY([VehicleId])
Fixed

2021-12-18 21:41 UTC, PushMeNow approved these changes

2021-12-19 15:03 UTC, kuzmiich approved these changes
(Advice) Put an empty line after all methods

2021-12-20 13:42 UTC, merged