Third week
Dev-incubator/WebAutoparkDenis pull request #3
Opened 2022-01-03 15:08 UTC by DenisCo1100100

Add controllers, views, models

2022-01-04 12:42 UTC, kuzmiich requested changes
double check all repositories carefully

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +            return View(_mapper.Map<IEnumerable<VehicleModel>>(componentsList));
Create additional variable to mapped objects.
Fix anywhere

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleTypeController.cs
> +            return View(_mapper.Map<VehicleTypeModel>(vehicleType));
Create additional variable.
Check anywhere

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark/Startup.cs
> +            services.AddAutoMapper
It's the oltdated way to map profiles

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark.BusinessLogic/Models/VehicleModel.cs
> +        [Required] public ColorType Color { get; set; }
Attribute should be added only for ViewModels ~ PresentationLayer.
Why your ViewModels did in Business Layer?

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark.BusinessLogic/Models/VehicleModel.cs
> +        public string RegistrationNumber { get; set; }
This properties must be required

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark.BusinessLogic/Models/VehicleTypeModel.cs
> +        public string Name { get; set; }
Must be required

2022-01-04 12:42 UTC, kuzmiich commented on WebAutopark.Core/Entities/VehicleType.cs
> +        public string Name { get; set; }
Why you add only name, where tax coefficient?

2022-01-04 21:39 UTC, ArtyomKolosov2 requested changes

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/ComponentController.cs
> +            }
Suggestion: nameof(Index), try to find all occurrences

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark.BusinessLogic/Models/ComponentModel.cs
> +    {
Suggestion: add to all business layer models classic `DTO` at the end. It will help more easily separate models from different levels when you are reading the code. And a reminder: Presentation layer - ViewModel, BusinessLayer - DTO, Data Access Layer - name of the entity.

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +        {
Same as here -> https://github.com/Dev-incubator/WebAutoparkMaksim/pull/3#discussion_r775182842 . Please check other places for this

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +            }
Issue: `return NotFound()`

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/Startup.cs
>              services.AddScoped<IRepository<VehicleType>, VehicleTypeRepository>();
Suggestion: Create extension method in Data Access layer and move there these DI configuration. Then directly call in this `Startup.cs`

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark.DataBaseAccess/WebAutopark.DataBaseAccess.csproj
>      <PackageReference Include="Dapper" Version="2.0.123" />
Question: What is this package (AutoMapperBuilder)? Do you really need it?

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        }
Question: I'm not sure what will happen if we will get an invalid model here. It will be just redirected back to Create page with all validation errors outputed?

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        }
Question: I've expect here the same approach for redirection like at lines 45 - 55. Check all the other places please

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark/WebAutopark.csproj.user
> +</Project>
I suppose you don't need this file. But I'm not sure

2022-01-04 21:39 UTC, ArtyomKolosov2 commented on WebAutopark.BusinessLogic/Models/VehicleModel.cs
> +        [Required] public ColorType Color { get; set; }
I agree. I was a little bit confused because of it. You services must not have Data Access layer models transfered from Presentation layer to Business layer. It can be ViewModels or DTO's (more preferable).

2022-01-05 09:42 UTC, PushMeNow requested changes

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Models/ComponentModel.cs
> +    {
I want to correct Artem's (@ArtyomKolosov2 ) topic about dtos. Use `Dto` at the end because using of caps in names of methods, variables etc. is bad practice.

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Models/VehicleModel.cs
> +        [Required] public ColorType Color { get; set; }
Also I want to suggest do not inline attributes and other code because difficult to read.

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark.BusinessLogic/WebAutopark.BusinessLogic.csproj
> +    <PackageReference Include="AutoMapperBuilder" Version="1.1.0" />
Why do you need this package?

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark.Core/Entities/VehicleType.cs
> +        public string Name { get; set; }
@kuzmiich I think it's my bad. I have created DB scheme without this field. @DenisCo1100100 revert pls Tax Coef. I'll correct scheme

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark/Controllers/ComponentController.cs
> +            return View(_mapper.Map<IEnumerable<ComponentModel>>(componentsList));
omg... have you read our chat? I've already written 'Do not inline method calling and variable initialization'. Fix everywhere.

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark/Startup.cs
> +            services.AddAutoMapper
[Here](https://docs.automapper.org/en/stable/Configuration.html) is the best way how to use and register mapping. For this purpose is used mapper profiles.

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark/Views/VehicleType/Index.cshtml
> +                    <a asp-controller="VehicleType" asp-action="Update" asp-route-id="@item.VehicleTypeId">Udpate</a>
*Update

2022-01-05 09:42 UTC, PushMeNow commented on WebAutopark/WebAutopark.csproj.user
> +</Project>
@ArtyomKolosov2 correct. It is part of local settings of project for VS. @DenisCo1100100 add it pls in gitignore and exclude from PR.

2022-01-05 21:04 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleController.cs
> +            return View(_mapper.Map<IEnumerable<VehicleModel>>(componentsList));
Fixed

2022-01-05 21:04 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +            return View(_mapper.Map<VehicleTypeModel>(vehicleType));
Fixed

2022-01-05 22:42 UTC, DenisCo1100100 commented on WebAutopark/Startup.cs
> +            services.AddAutoMapper
Fixed

2022-01-05 22:45 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Models/VehicleModel.cs
> +        public string RegistrationNumber { get; set; }
Fixed

2022-01-05 22:45 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Models/VehicleTypeModel.cs
> +        public string Name { get; set; }
Fixed

2022-01-06 10:03 UTC, DenisCo1100100 commented on WebAutopark/Startup.cs
> +            services.AddAutoMapper
Fixed

2022-01-06 10:04 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Models/VehicleModel.cs
> +        public string RegistrationNumber { get; set; }
Fixed

2022-01-06 10:04 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Models/VehicleTypeModel.cs
> +        public string Name { get; set; }
Fixed

2022-01-06 10:33 UTC, DenisCo1100100 commented on WebAutopark.Core/Entities/VehicleType.cs
> +        public string Name { get; set; }
Fixed

2022-01-06 10:33 UTC, DenisCo1100100 commented on WebAutopark/Controllers/ComponentController.cs
> +            }
Fixed

2022-01-06 10:36 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +            }
Fixed

2022-01-06 10:37 UTC, DenisCo1100100 commented on WebAutopark/Startup.cs
>              services.AddScoped<IRepository<VehicleType>, VehicleTypeRepository>();
Fixed

2022-01-06 10:56 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/WebAutopark.DataBaseAccess.csproj
>      <PackageReference Include="Dapper" Version="2.0.123" />
Fixed

2022-01-06 11:06 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        }
Fixed

2022-01-06 11:08 UTC, DenisCo1100100 commented on WebAutopark/Controllers/ComponentController.cs
> +            return View(_mapper.Map<IEnumerable<ComponentModel>>(componentsList));
Fixed

2022-01-06 11:32 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        }
It will simply be redirected back to the Create page

2022-01-06 11:33 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/WebAutopark.BusinessLogic.csproj
> +    <PackageReference Include="AutoMapperBuilder" Version="1.1.0" />
Removed

2022-01-06 11:33 UTC, DenisCo1100100 commented on WebAutopark/Views/VehicleType/Index.cshtml
> +                    <a asp-controller="VehicleType" asp-action="Update" asp-route-id="@item.VehicleTypeId">Udpate</a>
Fixed

2022-01-06 15:26 UTC, kuzmiich requested changes
Need a syntactic fix

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, double.MaxValue)]
```suggestion
        [Range(0d, double.MaxValue)] 
        public double Weight { get; set; }

        [Range(0d, double.MaxValue)] 
```

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Models/VehicleViewModel.cs
> +        public string Model { get; set; }
I also could add attribute to limit the string `StringLength`. (Non required)

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Models/OrderViewModel.cs
> +        [Required] public int VehicleId { get; set; }
Split attribute, pls.

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Models/OrderItemViewModel.cs
> +        public int Quantity { get; set; }
Are you sure, that this field is not required?

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleTypeController.cs
> +                var vehicleType = _mapper.Map<VehicleTypeDto>(vehicleTypeModel);
Fix variables name vehicleTypeModel and vehicleType.
You cast vehicleTypeModel variable (it's model or ViewModel???) to type VehicleTypeDto.

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        private readonly IDtoService<VehicleTypeDto> _vehicleTypeServicec;
```suggestion
        private readonly IDtoService<VehicleTypeDto> _vehicleTypeService;
```

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Models/ComponentViewModel.cs
> +        public string Name { get; set; }
Add `StringLength` attribute

2022-01-06 15:26 UTC, kuzmiich commented on WebAutopark/Models/VehicleTypeViewModel.cs
> +        public double TaxCoefficient { get; set; }
Add attributes to limit string and double props

2022-01-06 18:17 UTC, PushMeNow requested changes

2022-01-06 18:17 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/Base/BaseService.cs
> +    public abstract class BaseService<TDto, TEntity> : IDtoService<TDto>
Why DtoService? This name says me nothing. If you want to create common interface for services which will just transform data objects to business object so name it like IDataService. We can use DTOs not only in services. It is just source of transformation or transportation of data.

2022-01-06 18:17 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/Base/BaseService.cs
> +            var dtoItems = _mapper.Map<List<TDto>>(entities);
Well... Why here you map it in List but return for method IEnumerable? Mapper can map it in IEnumerable.

2022-01-06 18:17 UTC, PushMeNow commented on WebAutopark/Models/OrderItemViewModel.cs
> +        public int Quantity { get; set; }
@kuzmiich it is required. Range attribute means it in this case.

2022-01-07 01:20 UTC, DenisCo1100100 commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, double.MaxValue)]
Fixed

2022-01-07 01:20 UTC, DenisCo1100100 commented on WebAutopark/Models/VehicleViewModel.cs
> +        public string Model { get; set; }
Fixed

2022-01-07 01:20 UTC, DenisCo1100100 commented on WebAutopark/Models/OrderViewModel.cs
> +        [Required] public int VehicleId { get; set; }
Fixed

2022-01-07 01:21 UTC, DenisCo1100100 commented on WebAutopark/Models/ComponentViewModel.cs
> +        public string Name { get; set; }
Fixed

2022-01-07 01:37 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +                var vehicleType = _mapper.Map<VehicleTypeDto>(vehicleTypeModel);
Fixed

2022-01-07 01:37 UTC, DenisCo1100100 commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        private readonly IDtoService<VehicleTypeDto> _vehicleTypeServicec;
Fixed

2022-01-07 01:37 UTC, DenisCo1100100 commented on WebAutopark/Models/VehicleTypeViewModel.cs
> +        public double TaxCoefficient { get; set; }
Fixed

2022-01-07 01:41 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Services/Base/BaseService.cs
> +            var dtoItems = _mapper.Map<List<TDto>>(entities);
Fixed

2022-01-07 01:41 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/MapperProfiles/DtoEntitieProfile.cs
> +    public class DtoEntitieProfile : Profile
Fixed

2022-01-09 14:57 UTC, PushMeNow approved these changes

2022-01-11 20:59 UTC, kuzmiich approved these changes

2022-01-11 21:10 UTC, ArtyomKolosov2 approved these changes

2022-01-11 21:16 UTC, merged