Fourth week
Dev-incubator/WebAutoparkDenis pull request #4
Opened 2022-01-12 16:01 UTC by DenisCo1100100

Add Order and OrderItem controllers, view. Add sort vehicle table.

2022-01-13 05:27 UTC, kuzmiich requested changes

2022-01-13 05:27 UTC, kuzmiich commented on WebAutopark.BusinessLogic/Services/OrderItemService.cs
> +            return orderItems;
This variable is redundant, because this Linq expression not hard

2022-01-13 05:27 UTC, kuzmiich commented on WebAutopark.BusinessLogic/Services/VehicleService.cs
> +        IEnumerable<VehicleDto> IVehicleService.GetAllItems(SortCriteria sortCriteria, bool isAscending)
Are you really need an explicit interface conversion?

2022-01-13 05:27 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/OrderRepository.cs
> +        private readonly string QueryCreateOrder = "INSERT INTO Orders(VehicleId, Date) OUTPUT Inserted.OrderId, Inserted.VehicleId, Inserted.Date VALUES(@VehicleId, @Date) ";
This fields(Queries) should be a const.
Only const field referred to using `PascalCase`
Check all your fields

2022-01-13 05:27 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/VehicleRepository.cs
> +        private static string GetVehicleSortString(SortCriteria sortCriteria) => sortCriteria switch
Why this method on Data Access lvl?

2022-01-13 05:27 UTC, kuzmiich commented on WebAutopark.DataBaseAccess/Repository/VehicleRepository.cs
> +            var getSorted = isAscending ? $"{QueryGetAll} ORDER BY {GetVehicleSortString(sortCriteria)} ASC" :
This logic should be at Business Layer

2022-01-13 10:52 UTC, DenisCo1100100 commented on SQLScripts/dbo.Vehicles.Table.sql
>  CONSTRAINT [FK_Vehicles_VehicleTypes] FOREIGN KEY([VehicleTypeId]) REFERENCES [VehicleTypes]([VehicleTypesId]) ON DELETE CASCADE
Fixed

2022-01-13 10:54 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Services/OrderItemService.cs
> +            return orderItems;
Fixed

2022-01-13 11:01 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Services/VehicleService.cs
> +        IEnumerable<VehicleDto> IVehicleService.GetAllItems(SortCriteria sortCriteria, bool isAscending)
Fixed

2022-01-13 15:01 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/OrderRepository.cs
> +        private readonly string QueryCreateOrder = "INSERT INTO Orders(VehicleId, Date) OUTPUT Inserted.OrderId, Inserted.VehicleId, Inserted.Date VALUES(@VehicleId, @Date) ";
Fixed

2022-01-13 21:53 UTC, ArtyomKolosov2 approved these changes

2022-01-13 21:53 UTC, ArtyomKolosov2 commented on WebAutopark.BusinessLogic/Services/Interface/IVehicleService.cs
> +    }
Nitpick: remove public

2022-01-13 21:53 UTC, ArtyomKolosov2 commented on WebAutopark.BusinessLogic/Services/OrderItemService.cs
> +    }
Suggestion: implement method in repository to filter orders by id at DB level. It's better to avoid load all items to the memory and then perform filtering.

2022-01-13 21:53 UTC, ArtyomKolosov2 commented on WebAutopark.DataBaseAccess/Repository/OrderRepository.cs
>          public void Update(Order item) => Connection.Execute(QueryUpdate, item);
Question: @PushMeNow I'm just wondering why repositories & services are not async? Is something changed in the educational program?

2022-01-13 21:53 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/OrderItemController.cs
> +            IMapper mapper)
nitpick: formatting

2022-01-13 21:53 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/OrderController.cs
> +            IMapper mapper)
nitpick:  formatting

2022-01-13 21:53 UTC, ArtyomKolosov2 commented on WebAutopark.DataBaseAccess/Repository/VehicleRepository.cs
> +        private static string GetVehicleSortString(SortCriteria sortCriteria) => sortCriteria switch
Just saying, There is a lot ways how it can be implemented. You may create a new Service for providing this or move it to some static helper class or even move it to some DB table to make configurable from the outside (not hardcoded in the code)

2022-01-14 20:28 UTC, PushMeNow requested changes

2022-01-14 20:28 UTC, PushMeNow commented on WebAutopark.DataBaseAccess/Repository/OrderRepository.cs
>          public void Update(Order item) => Connection.Execute(QueryUpdate, item);
@ArtyomKolosov2 I decided main point of this project to acquaint deeply with SQL queries and to introduce architecture of application. Also they will read module about async/await only on third week of the project. So recently I have add new rule: they can use sync or async way - no matter.

2022-01-14 20:28 UTC, PushMeNow commented on WebAutopark.DataBaseAccess/Repository/VehicleRepository.cs
> +        private static string GetVehicleSortString(SortCriteria sortCriteria) => sortCriteria switch
@kuzmiich @ArtyomKolosov2 I have added mandatory requirement - they have to organize sorting on data access level. I'm no sure good idea to move this method in helper because it is specific logic only for orders. But @DenisCo1100100 move pls method at the end of this file because all private (static) method should be there.

2022-01-15 15:28 UTC, DenisCo1100100 commented on WebAutopark.DataBaseAccess/Repository/VehicleRepository.cs
> +        private static string GetVehicleSortString(SortCriteria sortCriteria) => sortCriteria switch
Fixed

2022-01-15 15:28 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Services/OrderItemService.cs
> +    }
Fixed

2022-01-15 15:34 UTC, DenisCo1100100 commented on WebAutopark/Controllers/OrderController.cs
> +            IMapper mapper)
Fixed

2022-01-15 15:35 UTC, DenisCo1100100 commented on WebAutopark/Controllers/OrderItemController.cs
> +            IMapper mapper)
Fixed

2022-01-15 15:35 UTC, DenisCo1100100 commented on WebAutopark.BusinessLogic/Services/Interface/IVehicleService.cs
> +    }
Fixed

2022-01-16 19:26 UTC, kuzmiich approved these changes

2022-01-18 14:08 UTC, PushMeNow approved these changes

2022-01-18 14:27 UTC, merged